from PySide6 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(601, 735)
        self.label_4 = QtWidgets.QLabel(parent=Form)
        self.label_4.setGeometry(QtCore.QRect(10, 280, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.desc_coffee = QtWidgets.QLineEdit(parent=Form)
        self.desc_coffee.setGeometry(QtCore.QRect(220, 250, 351, 151))
        self.desc_coffee.setObjectName("desc_coffee")
        self.pushButton = QtWidgets.QPushButton(parent=Form)
        self.pushButton.setGeometry(QtCore.QRect(210, 657, 111, 31))
        self.pushButton.setObjectName("pushButton")
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setGeometry(QtCore.QRect(10, 420, 571, 141))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.price_coffee = QtWidgets.QLineEdit(parent=self.widget)
        self.price_coffee.setObjectName("price_coffee")
        self.gridLayout.addWidget(self.price_coffee, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.volume_coffee = QtWidgets.QLineEdit(parent=self.widget)
        self.volume_coffee.setObjectName("volume_coffee")
        self.gridLayout.addWidget(self.volume_coffee, 1, 1, 1, 1)
        self.widget1 = QtWidgets.QWidget(parent=Form)
        self.widget1.setGeometry(QtCore.QRect(10, 50, 571, 191))
        self.widget1.setObjectName("widget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(parent=self.widget1)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.coffee_sort = QtWidgets.QLineEdit(parent=self.widget1)
        self.coffee_sort.setObjectName("coffee_sort")
        self.gridLayout_2.addWidget(self.coffee_sort, 0, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(parent=self.widget1)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.roast_coffee = QtWidgets.QComboBox(parent=self.widget1)
        self.roast_coffee.setObjectName("roast_coffee")
        self.roast_coffee.addItem("")
        self.roast_coffee.addItem("")
        self.roast_coffee.addItem("")
        self.gridLayout_2.addWidget(self.roast_coffee, 1, 1, 1, 2)
        self.label_3 = QtWidgets.QLabel(parent=self.widget1)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 2)
        self.type_coffee = QtWidgets.QComboBox(parent=self.widget1)
        self.type_coffee.setObjectName("type_coffee")
        self.type_coffee.addItem("")
        self.type_coffee.addItem("")
        self.gridLayout_2.addWidget(self.type_coffee, 2, 2, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_4.setText(_translate("Form", "Описание вкуса"))
        self.pushButton.setText(_translate("Form", "Ок"))
        self.label_5.setText(_translate("Form", "Цена(руб.)"))
        self.label_6.setText(_translate("Form", "Объем упаковки"))
        self.label.setText(_translate("Form", "Сорт"))
        self.label_2.setText(_translate("Form", "Степень ображки"))
        self.roast_coffee.setItemText(0, _translate("Form", "Средняя"))
        self.roast_coffee.setItemText(1, _translate("Form", "Тёмная"))
        self.roast_coffee.setItemText(2, _translate("Form", "Светлая"))
        self.label_3.setText(_translate("Form", "Молотый/в зёрнах"))
        self.type_coffee.setItemText(0, _translate("Form", "Молотый"))
        self.type_coffee.setItemText(1, _translate("Form", "В зёрнах"))